// kob-game/web/src/components/ContentBase.vue
<template>
    <div class="container">
        <div class="card">
            <div class="card-body">
                <slot></slot>
            </div>
        </div>
    </div>

</template>


<script>

export default {
    name: "ContentBase",



    

};


</script>


<style>

.container {
    margin: 20px auto;
}

</style>

// react-calculator/src/components/content/contentbase.jsx
import React, { Component } from 'react';


class ContentBase extends Component {
    state = {}
    render() {
        return (
            <React.Fragment>
                <div className="container" style={{margin: "20px auto"}}>
                    <div className="card">
                        <div className="card-body">
                            {this.props.children}
                        </div>
                    </div>
                </div>

            </React.Fragment>
        );
    }
}

export default ContentBase;
